name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build test
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Lint with clippy
        run: cargo clippy --all-targets --all-features

      - name: Check formatting
        run: cargo fmt --all --check
