# name: Development Workflow

# on:
#   push:
#     paths:
#       - 'core/**'
#       - 'web/**'
#   pull_request:
#     paths:
#       - 'core/**'
#       - 'web/**'

# jobs:
#   check-core:
#     name: Check Go Core
#     runs-on: ubuntu-latest
#     if: github.event_name == 'push' || github.event_name == 'pull_request'
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Go
#         uses: actions/setup-go@v4
#         with:
#           go-version: '1.21'

#       - name: Run go fmt if core/ is updated
#         run: |
#           if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep '^core/'; then
#             go fmt ./core/...
#           else
#             echo "No changes in core/"
#           fi

#   check-web:
#     name: Check Next.js Web
#     runs-on: ubuntu-latest
#     if: github.event_name == 'push' || github.event_name == 'pull_request'
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name: Install pnpm
#         run: npm install -g pnpm

#       - name: Run pnpm test if web/ is updated
#         run: |
#           if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep '^web/'; then
#             cd web
#             pnpm install
#             pnpm test
#           else
#             echo "No changes in web/"
#           fi
